sudo: required
language: node_js
services:
- docker
node_js:
- '5'
- '6'
before_install:
- docker pull elasticsearch:2
- docker pull rabbitmq:3
- docker run -d -p 9200:9200 -p 9300:9300 elasticsearch:2
- docker run -d -p 5671:5671 -p 5672:5672 -p 25672:25672 rabbitmq:3
- docker ps -a
install:
- npm install
script:
- npm run check
- npm run build
- npm run validate
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: panthro.rafael@gmail.com
  api_key:
    secure: c7vOmwD6h7NQrAPZNM7+Gs7nRCC4o0RmRUDJYCQ7Yy8b8zCHK7CI04uQorW5f3allEg9f1qs4GBqtKIosINLO4Nijw0yYVhXpKrCMhg90I1AZdF5guZf0SiMmM+Sw9WnrR9E27wmhSwTcSC1eylHL+lxjeXReNnNlDfGUvqZUW57MXV9lYCNBP9OwEkgMYPVodS/2jBbC5S/ZFn7Ce4OWdp9vE298NwnqWKHQHFF8GgWCqUz7JNPH1JH72+I+Dws7hAYbZTk5d9srqpnD+uNlWozwrfixeMmCn1EeIrfhuiqXIa7hedT0UxPs9qHtPgEBwSrGEAPpp3ulj1Xpn5NvVKKxZqxkxf7QFnRNOh1kTbyLHz+qTqJqJRGWUGbrlaA64KPZQeJJIfpDfTMeSRDdQ4D7hXMttksRSeTpf358oTwqqSFx2CFSAQk1IC4DNhkTBEv91+9ELJ+9eFasfVIVIl5oS1yty0XOKVviTAO0YMsGFV2vH6PfyEuLDbjRI2I7Vhw1uu//YsAjIaY3D3h9hds87XzoTPgiVE981L4u1UDtZQKWSisNy3lK7ZV934qRFvYSA3td0hfkr+7wImnsQCsR+MzjjDjP8J7nU4lHehxfzypC5VH8CsL3/HeWT48mm5V2DagBfWJf/d472rbXech1f84xk5q8Sjvx7QTL2w=
  on:
    branch: master
    tags: true
    repo: Notastica/data-feed-orchestrator
env:
  global:
    secure: V9sKxTCr5Q6DKGiZmvUM5W8WHLpY70SXywH2zsaq/PkxGvG2Bsbn8xxQqDfw8NAJhjwJ2Ex0zO4vX+K4ZwMlUuwSIBrOTxtPs/La2av2LVWfDm4p9447dcMooRBF8UFGlQLGH2FWQRDU/uV4rsrNwdk4IdAMI5TyYAvEwvRq9uTqXl2DPC4UH9B//0xFkEdaKawcfN8QMI0JLlPoGvlcvwluQrHYDWf63PlAEysIQsA+RDgkudvrVb6rYewjcjJxSZC6r4kFWFCdb2J46j58oYzopNy/oONGKQx32VlqA6l7Dr5PRTMcqHZqElzfLFk7NdQFKvOLQVGGog17WjObfbB/yAz6ZWyMuavbpm7BUpv+6nWU9FVFr5X2XNiXbBPgNb4B+dCLpgDrL9XTF1RPKdy13C+SzErOPKPhVSiZmZ8ei0n2TwME47zA6TqxcABPhbkDOA5wbohs/k1J/qFJG1ieYTw21T7XweLWUJobaHt5MadTZ6KtF2LSEeoV67nHzyty5TAPyyqDQunnAphv9mkth5u3LS3YXwW/dXt7ip5t63+OIdNWMw2EPt5Cbn4c1+jq08n9DuTrP0xS6DFx6kH4emoalMcC43mAkINLRDDM/TSfXZSfaNnsa6a4o4LsgvDoKZ9gcyklptycBGLinMpDh6RcKIgvGuI0FalWvtk=
